### PR TITLE
Fixes issue #74 - Critical racing condition on Stub Server while registering the calls

### PR DESCRIPTION
**Pull request by michelzanini**
This PR fixes the issue #74.

### CODE REVIEW

**Comment by mkotsur** [comment]
@michelzanini could you please rebase with the latest 0.9.x? CircleCI has changed and is not able to build the code anymore. I've made some changes to the CircleCI config and added Gradle Wrapper so that CircleCI would be able to run the tests again.

**Comment by michelzanini** [comment]
That's done now.

**Comment by mkotsur** [comment]
@michelzanini thanks for the very detailed analysis! Going to release 0.9.4 ASAP.

**Comment by michelzanini** [comment]
Its released and I am using the new release now. Thanks!

**Pull request merged**
