### PR TITLE
Address StubServer concurrency issues

### PR DESCRIPTION
**Pull request by brendan-hofmann**
- Replace ArrayLists with CopyOnWriteArrayLists
 - Remove now-unneeded synchronized block
 - Append to final stubs list instead of reassigning in constructor

[Review on Reviewable](https://reviewable.io/reviews/mkotsur/restito/34)

### CODE REVIEW

**Comment by mkotsur** [comment]
I was looking at `CopyOnWriteArrayLists` yesterday, but since it is mentioned that it has a lot of overhead on mutations, decided to just wrap into `new ArrayList`. However, you are right, problems can arise during copying, and performance impact is less relevant for test code.

**Comment by mkotsur** [comment]
Thanks a lot for this. Could you also remove wrapping into `new ArrayList()` in `getStubs()` and `getCalls()` then? Probably `unmodifiableList()` is not necessary too anymore.

https://github.com/mkotsur/restito/pull/34/files#diff-d947f4dc125589b8bfb1144e58d9bc25R171
https://github.com/mkotsur/restito/pull/34/files#diff-d947f4dc125589b8bfb1144e58d9bc25R164

**Comment by brendan-hofmann** [comment]
I think the unmodifiableList() wrapper should stay, otherwise those getters allow clients to violate the API contract implied by the rest of the class. I'll remove the new ArrayLists though, since those don't really add anything anymore.

**Comment by mkotsur** [comment]
Thanks!

**Pull request merged**
